version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"

  api:
    depends_on:
      - db
    image: api:latest
    ports:
      - "3308:8080"
    restart: always
    environment:
      API_DB_HOST: db:3306
      API_DB_PASSWORD: 123456

volumes:
  db_data: